import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * La barre latérale est générée automatiquement à partir de l'arborescence
 * du dossier `docs/`. Les préfixes numériques des dossiers (01-, 02-, ...)
 * fixent l'ordre des chapitres et sont retirés des URL.
 */
const sidebars: SidebarsConfig = {
  coursSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
